# QA4U lecture 3

## read csv file

In [2]:
import pandas as pd
df = pd.read_csv('QA4Uafter.csv',header=None)
df

0    1    2    3
0    3.0  3.0  3.0  3.0
1    2.0  2.0  3.0  3.0
2    4.0  3.0  4.0  5.0
3    4.0  3.0  3.0  4.0
4    3.0  2.0  3.0  6.0
..   ...  ...  ...  ...
241  2.0  3.0  3.0  4.0
242  4.0  2.0  3.0  4.0
243  1.0  1.0  1.0  1.0
244  4.0  2.0  3.0  3.0
245  4.0  2.0  5.0  2.0

[246 rows x 4 columns]

In [3]:
# convert into np format
import numpy as np
V = df.values.astype(np.int8)
print(V)

[[3 3 3 3]
 [2 2 3 3]
 [4 3 4 5]
 [4 3 3 4]
 [3 2 3 6]
 [3 3 3 5]
 [4 1 3 3]
 [3 2 2 2]
 [4 3 3 4]
 [2 3 3 3]
 [2 3 4 4]
 [4 2 2 4]
 [4 3 5 5]
 [2 1 2 4]
 [3 3 3 4]
 [2 2 3 2]
 [2 2 3 4]
 [2 2 3 3]
 [2 1 1 3]
 [2 1 3 1]
 [4 2 4 4]
 [2 1 3 5]
 [4 1 5 2]
 [2 2 3 1]
 [4 1 2 7]
 [4 2 3 4]
 [4 3 3 5]
 [4 1 3 3]
 [3 2 3 2]
 [4 3 3 5]
 [3 2 1 2]
 [2 1 3 4]
 [2 2 3 5]
 [4 2 2 4]
 [3 2 3 3]
 [4 2 2 1]
 [3 3 2 1]
 [2 2 3 5]
 [4 1 2 1]
 [4 3 3 3]
 [3 3 3 5]
 [3 1 3 5]
 [4 3 3 1]
 [1 2 1 4]
 [2 1 1 3]
 [4 1 3 1]
 [4 3 3 3]
 [4 3 3 4]
 [1 1 3 2]
 [2 1 2 1]
 [2 3 2 4]
 [4 2 2 1]
 [4 2 3 3]
 [2 1 2 5]
 [4 3 3 1]
 [4 1 2 4]
 [2 2 2 2]
 [4 3 3 1]
 [2 2 3 1]
 [2 2 3 4]
 [4 3 3 1]
 [3 2 3 5]
 [2 1 4 1]
 [4 2 5 2]
 [2 2 1 3]
 [4 3 3 1]
 [4 2 2 2]
 [2 1 2 5]
 [4 2 3 3]
 [2 2 3 5]
 [2 2 3 1]
 [4 3 5 3]
 [4 2 3 2]
 [2 2 3 3]
 [4 3 1 1]
 [4 3 3 3]
 [4 3 5 4]
 [3 3 2 2]
 [3 3 3 5]
 [4 3 2 1]
 [4 3 3 5]
 [2 2 1 2]
 [3 3 3 3]
 [2 1 2 3]
 [2 1 2 5]
 [3 3 2 1]
 [1 1 3 5]
 [4 2 2 2]
 [4 3 3 3]
 [4 2 2 4]
 [1 1 3 4]

In [4]:
# check size
N,M = V.shape
print(N,M)

246 4


## one-hot format 

In [5]:
def onehot(data):
  z = np.zeros(4+3+5+7)
  z[data[0]-1] = 1
  z[4+data[1]-1] = 1
  z[4+3+data[2]-1] = 1
  z[4+3+5+data[3]-1] = 1
  return z

In [6]:
# reshape raw-data
M = 4+3+5+7
Z = np.zeros(N*M).reshape(N,M)

for i in range(N):
  Z[i,:] = onehot(V[i,:])

In [7]:
# check the similarity of two data points
np.dot(Z[0,:], Z[1,:])

2.0

## two index inotations

To make our assumption more closer to the real world, we can consider not only which objects to be carried, but also who should carry, such as the following table

|$x_{ik}$  | Aさん | Bさん | Cさん | Dさん | Eさん |
|--:|------|------|------|------|------|
| 荷物A |      | 1    |      |      |      |
| 荷物B | 1    |      |      |      |      |
| 荷物C |      |      | 1    |      |      |
| 荷物D |      |      |      |      | 1    |
| 荷物E |      |      |      | 1    |      |

similar to the above idea, we can decide which person should belong to which group

|$x_{ik}$  | Aさん | Bさん | Cさん | Dさん | Eさん |
|--:|------|------|------|------|------|
| グループ１ |      | 1    |      |      |      |
| グループ2 | 1    |      |      |      |      |
| グループ3 |      |      | 1    |      |      |
| グループ4 |      |      |      |      | 1    |
| グループ5 |      |      |      | 1    |      |

the constraint is that, one person can only belong to one group
$$\sum_{k=1}^{K} x_{ik} = 1$$

the cost function based on penalty can be established as
$$\lambda \sum_{i=1}^{N} \left( \sum_{k=1}^{K} x_{ik} - 1 \right)^2$$

## cost function
Over all, our purpose for this grouping (clustering) is to ensure the variaty of each group.<br>
In other words, we want to min the similarity in each group, so that
$$E({\bf x}) = \sum_{k=1}^{K} \sum_{i \neq j} \left( \sum_{m}Z_{i,m}Z_{j,m} \right) x_{i,k}x_{j,k} + \lambda_1 \sum_{i=1}^{N} \left( \sum_{k=1}^{K} x_{ik} - 1 \right)^2$$
where $Z_{ij}$ is the one-hot similarity

In [8]:
from pyqubo import Array
K = 41
# バイナリ変数
x = Array.create(name='x', shape=(N,K), vartype='BINARY')

In [9]:
# compute Z in advance
Zmat = np.dot(Z,Z.T)

QUBO can be established from cost function
$$\lambda_1 \sum_{i=1}^{N} \left( \sum_{k=1}^{K} x_{ik} - 1 \right)^2 = \lambda_1 \sum_{i=1}^{N} \left( \sum_{k=1}^{K} x_{ik} - 1 \right)\left( \sum_{l=1}^{K} x_{il} - 1 \right) = 
\lambda_1 \sum_{i=1}^{N}\sum_{k=1}^{K} \sum_{l=1}^{K} x_{ik} x_{il}  - 2 \lambda_1 \sum_{i=1}^{N}\sum_{k=1}^{K} x_{ik} + \lambda_1 N$$

In [10]:
# only the second item
lam1 = 20.0
K = 41

QUBO = {}
for i in range(N):
  for k in range(K):
    for l in range(K):
      QUBO[(i+k*N,i+l*N)] = lam1
      if k == l:
        QUBO[(i+k*N,i+l*N)] = QUBO[(i+k*N,i+l*N)] - 2*lam1

In [11]:
# add the first item
for k in range(K):
  for i in range(N):
    for j in range(N):
      if i != j:
        if (i+k*N,j+k*N) not in QUBO.keys():
          QUBO[(i+k*N,j+k*N)] = Zmat[i,j]
        else:
          QUBO[(i+k*N,j+k*N)] = QUBO[(i+k*N,j+k*N)] + Zmat[i,j]

QA time

In [15]:
from openjij import SQASampler
sim_sampler = SQASampler()

# wait for a little bit long time due to large prob size
sampleset = sim_sampler.sample_qubo(QUBO)
# print(sampleset.record)
# print(sampleset.first)

In [17]:
# check whether the res satisfies constraints
# 1: satisfied, others: no
ans = sampleset.record[0][0].reshape(N,K)
np.sum(ans,axis=1)

array([0, 0, 1, 2, 2, 3, 0, 3, 0, 0, 1, 3, 3, 0, 1, 1, 1, 0, 3, 0, 1, 0,
       1, 1, 1, 2, 1, 0, 1, 2, 2, 0, 0, 1, 2, 1, 1, 1, 2, 2, 1, 0, 1, 0,
       0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 4, 0, 1, 1, 0, 1, 3, 2, 1, 0,
       1, 2, 1, 0, 1, 1, 2, 0, 0, 3, 2, 1, 1, 0, 2, 0, 1, 2, 1, 0, 2, 0,
       1, 1, 0, 2, 0, 0, 1, 2, 1, 0, 0, 3, 2, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       2, 0, 2, 1, 1, 1, 0, 2, 0, 3, 1, 1, 0, 1, 1, 1, 1, 0, 1, 2, 2, 0,
       1, 2, 2, 1, 1, 0, 2, 1, 1, 0, 1, 0, 2, 2, 0, 0, 1, 0, 2, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 2, 2, 0, 0, 2, 0, 1, 1, 3, 1, 1, 0, 0, 0, 2,
       0, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 2, 1, 2, 0, 0, 1, 2, 2, 0, 1, 0,
       0, 1, 2, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 3, 3, 1, 0, 0, 2, 0, 2, 0,
       1, 1, 1, 1, 1, 2, 0, 1, 0, 1, 1, 1, 0, 3, 0, 1, 2, 1, 1, 2, 1, 3,
       0, 1, 1, 0])

In [18]:
# check how many people in a group
np.sum(ans,axis=0)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

### add num(member) constraint to the cost function
lets assume we want just 6 people in a group
$$\sum_{i=1}^N x_{ik} = 6$$
to use penalty method, we can say
$$\lambda_2 \sum_{k=1}^K \left( \sum_{i=1}^N x_{ik} - 6 \right)^2$$

rearrange the equation, we can get
\begin{equation}
\lambda_2 \sum_{k=1}^K \left( \sum_{i=1}^N x_{ik} - 6 \right)^2 = \lambda_2 \sum_{k=1}^K \left( \sum_{i=1}^N x_{ik} - 6 \right)\left( \sum_{j=1}^N x_{jk} - 6 \right)
\end{equation}
\begin{equation}
= 
\lambda_2 \sum_{k=1}^K \sum_{i=1}^N \sum_{j=1}^N x_{ik}x_{jk} - 12\lambda_2 \sum_{i=1}^N x_{ik} + 36 \lambda_2 K
\end{equation}

In [19]:
# add the new item to QUBO
lam2 = 3.0
for k in range(K):
  for i in range(N):
    for j in range(N):
      QUBO[(i+k*N,j+k*N)] = QUBO[(i+k*N,j+k*N)] + lam2
      if i == j:
        QUBO[(i+k*N,j+k*N)] = QUBO[(i+k*N,j+k*N)] - 2*6*lam2

In [24]:
# check res
sampleset = sim_sampler.sample_qubo(QUBO)
ans = sampleset.record[0][0].reshape(N,K)
np.sum(ans,axis=1)

array([3, 0, 2, 0, 0, 1, 0, 0, 1, 1, 1, 2, 2, 3, 1, 0, 0, 1, 1, 2, 2, 1,
       0, 0, 0, 1, 0, 2, 1, 1, 2, 0, 1, 1, 2, 0, 0, 1, 1, 2, 0, 1, 2, 1,
       0, 1, 0, 2, 3, 1, 1, 0, 1, 0, 1, 2, 3, 0, 0, 0, 0, 1, 2, 0, 1, 2,
       1, 2, 0, 1, 0, 2, 2, 0, 0, 0, 2, 2, 0, 1, 0, 0, 4, 0, 2, 1, 0, 1,
       1, 0, 1, 2, 0, 1, 1, 1, 1, 0, 1, 0, 3, 1, 0, 0, 2, 3, 1, 0, 1, 0,
       2, 0, 2, 1, 4, 1, 0, 0, 1, 1, 1, 1, 0, 2, 0, 2, 1, 1, 0, 1, 2, 1,
       0, 1, 2, 0, 0, 2, 1, 0, 0, 3, 1, 2, 1, 1, 2, 1, 1, 0, 0, 3, 0, 0,
       3, 1, 0, 2, 2, 0, 2, 0, 1, 0, 2, 1, 1, 1, 0, 0, 1, 2, 2, 1, 0, 0,
       2, 1, 1, 2, 1, 0, 1, 3, 0, 1, 0, 4, 1, 0, 1, 0, 2, 2, 0, 1, 1, 0,
       0, 0, 1, 2, 0, 3, 1, 0, 0, 3, 1, 1, 1, 0, 2, 0, 2, 2, 1, 2, 0, 2,
       0, 1, 0, 4, 1, 1, 0, 0, 1, 0, 3, 0, 0, 2, 2, 1, 1, 1, 1, 1, 1, 0,
       1, 2, 1, 0])

In [25]:
# check how many people in a group
np.sum(ans,axis=0)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [27]:
# check who is in which group
## will get error if ans does not fully satisfied our defined constraints

group_num = np.zeros(N)
for i in range(N):
  temp = np.where(ans[i,:]==1)[0][0]
  group_num[i] = temp
  print("{0} : {1}".format(i,temp))

0 : 6


IndexError: index 0 is out of bounds for axis 0 with size 0